# Generated by Django 3.0.8 on 2020-08-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200728_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.UserProfile'),
        ),
    ]
